spring:
  application:
    name: pj

  cloud:
    discovery:
      enabled: true

  datasource:
    url: ${URL:jdbc:mysql://localhost:3306/blog?useSSL=false&serverTimezone=UTC}
    username: ${USER:root}
    password: ${PASSWORD:12345}
#jdbc:mysql://mysql.railway.internal:3306/railway
#RoYCxrNLEcmPhpAUONGiinViwDWTNuAo
#  cache:
#    type: caffeine

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        max_fetch_depth: 1

server:
  port: ${PORT:8080} # ✅ Railway provides PORT env var; default fallback should be 8080

logging:
  level:
    root: INFO
    org:
      springframework:
        security: DEBUG
      hibernate:
        SQL: DEBUG

jwt:
  secret: dXoaYH1h2v3fBLOyqv5kqyb5uV9XWgW9XKqFwHrhGfg=
  expiration: 3600000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${DEFAULTZONE:http://localhost:8761/eureka/}
#https://donefor.up.railway.app/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true # ✅ `circuitbreakers` must match your library (resilience4j-health)

resilience4j:
  circuitbreaker:
    instances:
      commentBreaker:
        slidingWindowSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        slowCallRateThreshold: 50
        slowCallDurationThreshold: 2000
        permittedNumberOfCallsInHalfOpenState: 5
        waitDurationInOpenState: 10s
        automaticTransitionFromOpenToHalfOpenEnabled: true
        registerHealthIndicator: true
