spring:
  application:
    name: pj

  cloud:
    discovery:
      enabled: true

  datasource:
    url: jdbc:mysql://mysql.railway.internal:3306/railway
    username: root
    password: RoYCxrNLEcmPhpAUONGiinViwDWTNuAo

  cache:
    type: caffeine

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

server:
  port: ${PORT:8089}

logging:
  level:
    root: DEBUG
    org:
      springframework:
        security: DEBUG
      hibernate:
        SQL: DEBUG

jwt:
  secret: dXoaYH1h2v3fBLOyqv5kqyb5uV9XWgW9XKqFwHrhGfg=
  expiration: 3600000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: https://donefor.up.railway.app/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health
  health:
    circuit-breakers:
      enabled: true
  endpoint:
    health:
      show-details: always

resilience4j:
  circuitbreaker:
    instances:
      commentBreaker:
        sliding-window-size: 10
        failure-rate-threshold: 50
        minimum-number-of-calls: 5
        slow-call-rate-threshold: 50
        slow-call-duration-threshold: 2000ms
        permitted-number-of-calls-in-half-open-state: 5
        wait-duration-in-open-state: 10s
        automatic-transition-from-open-to-half-open-enabled: true
        register-health-indicator: true
